#!/usr/xpg4/bin/sh -e

# Options

PREFIX=${BUILDPREFIX}

TT=${BUILD_ROOT}/cfbuild-librsync${PREFIX}
TTD=${BUILD_ROOT}/cfbuild-librsync-devel${PREFIX}

# Patch
# Solaris 8

# Build

cmake -DCMAKE_INSTALL_PREFIX=${PREFIX} -DCMAKE_BUILD_TYPE=Release .

$MAKE

# Test

# Install

mkdir -p $TTD/lib
mkdir -p $TTD/include
$MAKE install prefix=${TTD}

# Package


mkdir -p ${TT}/lib
mv ${TTD}/lib/*.so* ${TT}/lib
