#!/usr/xpg4/bin/sh -e

# Options

PREFIX=${BUILDPREFIX}

TT=${BUILD_ROOT}/cfbuild-librsync${PREFIX}
TTD=${BUILD_ROOT}/cfbuild-librsync-devel${PREFIX}

# Patch
# Solaris 8

# Build

for i in 00*.patch
do
    $PATCH -p1 < $i
done

# Touch this file, or else autoreconf is called for some reason
touch config.hin
./configure --prefix=$PREFIX

$MAKE

# Test

# Install

mkdir -p $TTD/lib
mkdir -p $TTD/include
$MAKE install prefix=${TTD}

# Package


mkdir -p ${TT}/lib
mv ${TTD}/lib/*.so* ${TT}/lib
