# Dependency: apache
name=apache
version=2.4.66
source=httpd-2.4.66.tar.gz
roles=hub
build_type=custom
build_script=apache.sh
source_dir=httpd-2.4.66
patches=apachectl.patch fixed-implicit-decl-gettid.patch
