# Dependency: apr-util
name=apr-util
version=1.6.3
source=apr-util-1.6.3.tar.gz
roles=hub
build_type=autoconf
configure_flags=--with-apr=@PREFIX@ --with-ldap-lib=@PREFIX@/lib --with-ldap --with-expat=@PREFIX@
