# Dependency: git
name=git
version=2.52.0
source=git-2.52.0.tar.gz
roles=hub
build_type=autoconf
configure_flags=--without-tcltk --without-iconv --with-openssl=@PREFIX@ --with-zlib=@PREFIX@ --with-curl=@PREFIX@ --with-gitconfig=@PREFIX@/config/gitconfig --with-gitattributes=@PREFIX@/config/gitattributes --libexecdir=@PREFIX@/lib
make_flags=CURL_LDFLAGS="-lcurl"
