# Dependency: libcurl-hub
name=libcurl-hub
version=8.17.0
source=curl-8.17.0.tar.gz
roles=hub
build_type=autoconf
source_dir=curl-8.17.0
configure_flags=--with-openssl=@PREFIX@ --without-libidn2 --disable-ldap --disable-ldaps --disable-ntlm --without-libpsl --without-librtmp --without-libssh2 --without-nghttp2 --without-gnutls --without-gssapi --without-winidn
