# Dependency: libcurl
name=libcurl
version=8.17.0
source=curl-8.17.0.tar.gz
roles=agent
build_type=autoconf
source_dir=curl-8.17.0
configure_flags=--with-openssl=@PREFIX@ --without-libidn2 --disable-ldap --without-libpsl --disable-dict --disable-gopher --disable-imap --disable-mqtt --disable-pop3 --disable-rtsp --disable-smb --disable-smtp --disable-telnet --disable-tftp
