# Dependency: openssl
name=openssl
version=3.6.0
source=openssl-3.6.0.tar.gz
roles=agent hub
build_type=custom
build_script=openssl.sh
patches_aix=0006-Add-latomic-on-AIX-7.patch 0008-Define-_XOPEN_SOURCE_EXTENDED-as-1.patch
patches_solaris=0009-Define-_XOPEN_SOURCE-as-600-on-Solaris-SPARC.patch
patches_hpux=fixed-undeclared-identifier.patch
