pkg_update=apt-get update
pkg_install=apt-get install -y --no-install-recommends
pkg_clean=rm -rf /var/lib/apt/lists/*
build_prereqs=build-essential autoconf automake libtool bison flex git wget curl ca-certificates pkg-config libpam0g-dev libssl-dev rsync fakeroot dpkg-dev debhelper sudo cmake patch
