pkg_update=zypper --non-interactive refresh
pkg_install=zypper --non-interactive install -y
pkg_clean=zypper clean --all
build_prereqs=gcc gcc-c++ make autoconf automake libtool bison flex git wget curl ca-certificates pkg-config pam-devel libopenssl-devel rpm-build rsync sudo which cmake patch
