#!/bin/sh -e

# Options

PREFIX=${BUILDPREFIX}

TT=${BUILD_ROOT}/cfbuild-librsync${PREFIX}
TTD=${BUILD_ROOT}/cfbuild-librsync-devel${PREFIX}

# Build

touch config.hin
./configure --prefix=$PREFIX
gmake

# Test

# Install

mkdir -p $TTD/lib
mkdir -p $TTD/include
gmake install prefix=${TTD}

# Package

mkdir -p ${TT}/lib
mv ${TTD}/lib/*.so* ${TT}/lib
