# Platform: IBM AIX
os_family=aix
packaging=aix
dep_packaging=rpm
shell=/bin/sh
make=gmake
patch=patch
fuser=/usr/sbin/fuser
cc=gcc
sha256_cmd=openssl dgst -sha256
sed_inplace=no
has_mktemp=no
has_systemd=no
rpath_flag=
ldflags=-Wl,-brtl -L@PREFIX@/lib -Wl,-blibpath:@PREFIX@/lib:/usr/lib:/lib
cflags=
path_prepend=/opt/freeware/gcc6/bin:/opt/freeware/bin
extra_deps=libgcc libiconv
