# Platform: FreeBSD
os_family=freebsd
packaging=freebsd
dep_packaging=freebsd
shell=/bin/sh
make=gmake
patch=patch
fuser=fuser
cc=cc
sha256_cmd=sha256
sed_inplace=no
has_mktemp=yes
has_systemd=no
rpath_flag=-Wl,-rpath,
ldflags=-L@PREFIX@/lib -Wl,-rpath,@PREFIX@/lib
cflags=
path_prepend=/usr/local/bin
extra_deps=
