# Platform: Ubuntu (same as Debian)
os_family=linux
packaging=deb
dep_packaging=deb
shell=/bin/sh
make=make
patch=patch
fuser=fuser
cc=cc
sha256_cmd=sha256sum
sed_inplace=yes
has_mktemp=yes
has_systemd=yes
rpath_flag=-Wl,-rpath,
ldflags=-L@PREFIX@/lib -Wl,-rpath,@PREFIX@/lib
cflags=
cppflags=-I@PREFIX@/include
path_prepend=
