# Platform: Windows (MinGW cross-compilation from Linux)
os_family=mingw
packaging=mingw
dep_packaging=deb
shell=/bin/sh
make=make
patch=patch
fuser=fuser
cc=cc
sha256_cmd=sha256sum
sed_inplace=yes
has_mktemp=yes
has_systemd=no
rpath_flag=
ldflags=-static-libgcc -L@PREFIX@/lib
cflags=
path_prepend=
extra_deps=pthreads-w32 libgnurx
